### ISSUE TITLE
Place relative style modules at the end

### ISSUE THREAD

**Issue by tejasjadhav** [mike1808/import-sort-style-react#1]
First of all, thank you for this amazing style. I've searching some React specific styles and after testing dozens of import styles, this one does the best sorting.

However, I have encountered one issue. Currently, relative CSS modules which are imported are put on top of other modules. The placement of the CSS modules should be at the end of all other modules.

In the current scenario, I get this,
```javascript
import './index.css';

import React from 'react';
```

instead of,
```javascript
import React from 'react';

import './index.css';
```

**Comment by mike1808** [comment]
Thanks for opening this issue. I've merged your PR and published `0.4.0` version.
